ARG RUBY_VERSION
ARG ALPINE_VERSION
FROM ruby:${RUBY_VERSION}-alpine${ALPINE_VERSION} as Builder
ARG ALPINE_VERSION

RUN apk add --update --no-cache \
  cmake \
  libcurl \
  tzdata \
  libpq \
  less \
  git \
  build-base \
  openssl-dev

WORKDIR /app
COPY docker/gitconfig /root/.gitconfig

COPY docker/entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
ENV BUNDLE_PATH=/bundle/alpine_${ALPINE_VERSION}/${RUBY_VERSION} \
    BUNDLE_BIN=/bundle/alpine_${ALPINE_VERSION}/${RUBY_VERSION}/bin \
    GEM_HOME=/bundle/alpine_${ALPINE_VERSION}/${RUBY_VERSION} \
    PATH=$PATH:/app/bin
